### ISSUE TITLE
Building error on macOS 14.5 arm64: Unknown Type '__pid_t' in modules/xumes/server_connection.h

### ISSUE THREAD

**Issue by viniciusmioto** [mastainvin/Xumes#54] opened 2024-06-19 21:11 UTC
# Building error on macOS 14.5 arm64: Unknown Type '__pid_t' in modules/xumes/server_connection.h

## Description 

Compilation Error: Unknown type name '__pid_t' in modules/xumes/server_connection.h

Occurs by running the command `scons platform=macos arch=arm64` on a macOS 14.5 (23F79) arm64 system.

## Output

```
[ 51%] Compiling modules/webxr/webxr_interface_js.cpp ...
[ 51%] Compiling modules/xumes/event_factory.cpp ...
[ 51%] Compiling modules/xumes/feature_node.cpp ...
[ 51%] Compiling modules/xumes/game_state_builder.cpp ...
[ 51%] Compiling modules/xumes/input_handler.cpp ...
[ 51%] Compiling modules/xumes/register_types.cpp ...
In file included from modules/xumes/feature_node.cpp:9:
In file included from modules/xumes/feature_node.h:14:
modules/xumes/server_connection.h:20:18: error: unknown type name '__pid_t'; did you mean 'pid_t'?
static std::map<__pid_t, ServerConnection*> serverConnections;
^~~~~~~
pid_t
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/sys/_types/_pid_t.h:31:31: note: 'pid_t' declared here
typedef __darwin_pid_t pid_t;
^
1 error generated.
scons: *** [modules/xumes/feature_node.macos.editor.arm64.o] Error 1
In file included from modules/xumes/register_types.cpp:9:
In file included from modules/xumes/feature_node.h:14:
modules/xumes/server_connection.h:20:18: error: unknown type name '__pid_t'; did you mean 'pid_t'?
static std::map<__pid_t, ServerConnection*> serverConnections;
^~~~~~~
pid_t
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/sys/_types/_pid_t.h:31:31: note: 'pid_t' declared here
typedef __darwin_pid_t pid_t;
^
1 error generated.
scons: *** [modules/xumes/register_types.macos.editor.arm64.o] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:33.325]
```

## Attempted Fix:

I tried changing the type `__pid_t` to `pid_t` in the file modules/xumes/server_connection.h to match the correct type declaration. The building was complete successfully. 

Although the following warnings were shown:

```
[ 51%] Compiling modules/xumes/xumes_communication_thread.cpp ...
[ 52%] Compiling platform/web/api/api.cpp ...
modules/xumes/server_connection.cpp:136:2: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
        sprintf(str, "%d", response);
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/stdio.h:180:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/sys/cdefs.h:218:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
[ 52%] In file included from modules/xumes/server_connection.cpp:12:
modules/xumes/server_connection.h:27:6: warning: private field 'opt' is not used [-Wunused-private-field]
        int opt = 1;
            ^
[ 52%] 2 warnings generated.
[ 53%] Compiling platform/android/export/export.cpp ...
```

# Runtime error

After the describe code change was made, the Godot editor crashes while playing a game:

<img width="580" alt="Screenshot 2024-06-19 at 3 03 02 PM" src="https://github.com/mastainvin/Xumes/assets/60669449/59561578-b58a-4223-85b6-cf189b85b9bd">

## Output

```
Godot Engine v4.3.dev.custom_build.ddf279c48 - https://godotengine.org
Vulkan API 1.2.283 - Forward+ - Using Vulkan Device #0: Apple - Apple M3
WARNING: Invalid/corrupt pipelines cache.
     at: pipeline_cache_create (drivers/vulkan/rendering_device_driver_vulkan.cpp:2248)
 
HTTP Server started on  8080
Godot Engine v4.3.dev.custom_build.ddf279c48 - https://godotengine.org
Vulkan API 1.2.283 - Forward+ - Using Vulkan Device #0: Apple - Apple M3
WARNING: Invalid/corrupt pipelines cache.
     at: pipeline_cache_create (drivers/vulkan/rendering_device_driver_vulkan.cpp:2248)
WARNING: A Thread object is being destroyed without its completion having been realized.
Please call wait_to_finish() on it to ensure correct cleanup.
     at: ~Thread (core/os/thread.cpp:107)
godot.macos.editor.arm64(22359,0x207a18c00) malloc: *** error for object 0x6000000db770: pointer being freed was not allocated
godot.macos.editor.arm64(22359,0x207a18c00) malloc: *** set a breakpoint in malloc_error_break to debug
```

## Xumes Play execution

By trying the following command `python -m xumes play --features_path=./tests/fruit_spawn/features --steps_path=./tests/fruit_spawn/features/steps -i 5 --tags=manual`. I got the following error:

```
Godot Engine v4.3.dev.custom_build.ddf279c48 - https://godotengine.org
Vulkan API 1.2.283 - Forward+ - Using Vulkan Device #0: Apple - Apple M3
WARNING: Invalid/corrupt pipelines cache.
     at: pipeline_cache_create (drivers/vulkan/rendering_device_driver_vulkan.cpp:2248)
 
setsockopt: Protocol not available
ERROR: BUG: Unreferenced static string to 0: _compression
   at: unref (core/string/string_name.cpp:127)
ERROR: BUG: Unreferenced static string to 0: Variant
   at: unref (core/string/string_name.cpp:127)
libc++abi: terminating due to uncaught exception of type std::__1::system_error: recursive_mutex lock failed: Invalid argument
```

**Comment by mastainvin** [comment] 2024-06-22 13:06
Hi @viniciusmioto,

Thank you for the issue. I will update the code according to your modifications.

Regarding the runtime error, it appears that the problem is with the setsockopt call. On macOS, the SO_REUSEPORT option is not available. I will modify the code to remove this option.

```
if (setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR | SO_REUSEPORT, &opt, sizeof(opt))) {
  perror("setsockopt");
  exit(EXIT_FAILURE);
}
```

I will also ensure that SO_REUSEPORT is set conditionally if it is supported by the platform.

**Comment by mastainvin** [comment] 2024-06-22 13:19
Hi @viniciusmioto, can you try to pull the modification from the `xumes` branch in the Godot repo and tell me if that fixed the issue? Also, were you using a mac before?

**Comment by viniciusmioto** [comment] 2024-06-22 20:29
Hi @mastainvin,

## macOS

I tried to pull the new Godot version from the xumes branch. I noticed that the runtime error I mentioned before only happens when I close the game. While it does not cause a major problem, I can still run the game properly.

I also tried running `python -m xumes play --features_path=./tests/fruit_spawn/features --steps_path=./tests/fruit_spawn/features/steps -i 5 --tags=manual` with **xumes==0.1.2**. 

Now it is not crashing either the Godot Editor or the Python terminal, but it is loading the game window forever without starting the game scene, so I can't test it.

```
➜  ./bin/godot.macos.editor.arm64 --editor --path ../royal_knight
Godot Engine v4.3.dev.custom_build.14d4a2d28 - https://godotengine.org
Vulkan API 1.2.283 - Forward+ - Using Vulkan Device #0: Apple - Apple M3
WARNING: Invalid/corrupt pipelines cache.
     at: pipeline_cache_create (drivers/vulkan/rendering_device_driver_vulkan.cpp:2248)
 
HTTP Server started on  8080
Godot Engine v4.3.dev.custom_build.14d4a2d28 - https://godotengine.org
Vulkan API 1.2.283 - Forward+ - Using Vulkan Device #0: Apple - Apple M3
WARNING: Invalid/corrupt pipelines cache.
     at: pipeline_cache_create (drivers/vulkan/rendering_device_driver_vulkan.cpp:2248)
```

No output was shown in the Python terminal.

## Linux (Ubuntu 22.04)

The manual test was working previously on my Linux machine, but since I updated xumes to the **0.1.2** version, it is no longer working. The game crashes and this is the output:

```
➜  ./bin/godot.linuxbsd.editor.x86_64 --editor --path ../royal_knight
Godot Engine v4.3.dev.custom_build.14d4a2d28 - https://godotengine.org
Vulkan API 1.3.255 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon Vega 10 Graphics (RADV RAVEN)
 
HTTP Server started on  8080
Godot Engine v4.3.dev.custom_build.14d4a2d28 - https://godotengine.org
Vulkan API 1.3.255 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon Vega 10 Graphics (RADV RAVEN)
 
WARNING: A Thread object is being destroyed without its completion having been realized.
Please call wait_to_finish() on it to ensure correct cleanup.
     at: ~Thread (core/os/thread.cpp:105)
free(): invalid pointer
```

Again, no output was shown in the Python terminal.

**Comment by mastainvin** [comment] 2024-06-22 22:01
Hi @viniciusmioto,

To get more detailed insights into the issue you're facing with the xumes CLI, please use the --info option:

```
ERROR:Traceback (most recent call last):
  File "/home/vincent/Documents/Xumes/src/xumes/modules/script/script.py", line 20, in execute
    if self.terminated():
  File "/home/vincent/Documents/Xumes/src/xumes/modules/human/human_playing_test_manager.py", line 16, in terminated
    return self._behavior.terminated()
  File "/home/vincent/Documents/Xumes_project/royal_knight/tests/fruit_spawn/features/steps/fruit_spawner.py", line 70, in terminated
    terminated = self.dead != 0 or self.score >= 1
AttributeError: 'CatchFruits' object has no attribute 'dead'
```

In the previous update (version 0.1.1), I moved the attributes under the context object. So where you used to have self.dead, it’s now self.context.dead. Like this:
```
terminated = self.context.dead != 0 or self.context.score >= 1
```

Sorry about the mix-up! I’ll make sure to flag these kinds of changes better in the future. Maybe we could add clearer notes or send out a heads-up when things change.

Feel free to close the issue if you've managed to fix the problem.

Have a good day!

**Closed as completed** 2024-06-26 13:01 UTC
Labels: bug
